spring:
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27017/persondatabase?authSource=admin

  cloud:
    stream:
      bindings:
        processPerson-in-0:
          destination: register-person
          group: person-consumer-group
          content-type: application/json
        processPerson-out-0:
          destination: register-person-publisher
          content-type: application/json
  jackson:
    serialization:
      write-dates-as-timestamps: false